project_id = "xglagkbblribtztkkovo"

[functions.get-public-report]
verify_jwt = false

[functions.get-public-share]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.get-logo-url]
verify_jwt = false

[functions.sign-public-report]
verify_jwt = false

[functions.sign-public-quote]
verify_jwt = false

[functions.get-db-size]
verify_jwt = false

[functions.get-manifest]
verify_jwt = false

[functions.get-public-quote]
verify_jwt = false

[functions.save-signed-pdf]
verify_jwt = false
